### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by githubuser77777**
Added tested tweaks and themes that work, corrected some listed tweaks

### CODE REVIEW

**Comment by Loy6410** [comment]
thanks for tested tweaks and corrections, but are you sure carbridge works? some people say it doesnt...

**Comment by rilodroid** [comment]
- iNstaKiller - iKarwan
- Lynx - Havoc
- QuickPrefs - AnthoPak
- YouTubeKiller - iKarwan

**Comment by Loy6410** [comment]
> - iNstaKiller - iKarwan
> 
> - Lynx - Havoc
> 
> - QuickPrefs - AnthoPak
> 
> - YouTubeKiller - iKarwan

thanks!

**Comment by githubuser77777** [comment]
> thanks for tested tweaks and corrections, but are you sure carbridge works? some people say it doesnt...

It doesn’t work from my tests, you can remove it

**Pull request closed without merging**
